-- ============================================
-- board_learn :: Categories (product taxonomy)
-- Run this in Supabase Dashboard > SQL Editor
-- AFTER schema.sql (depends on public.is_admin())
-- ============================================

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete cascade,
  name text not null,
  slug text,
  image_path text,
  display_type text not null default 'tile' check (display_type in ('tile', 'link')),
  href text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists categories_parent_id_idx on public.categories (parent_id);
create index if not exists categories_sort_idx on public.categories (sort_order);

-- RLS
alter table public.categories enable row level security;

drop policy if exists "active categories are viewable by everyone" on public.categories;
create policy "active categories are viewable by everyone"
  on public.categories for select
  using (is_active = true or public.is_admin());

drop policy if exists "admin can insert categories" on public.categories;
create policy "admin can insert categories"
  on public.categories for insert
  with check (public.is_admin());

drop policy if exists "admin can update categories" on public.categories;
create policy "admin can update categories"
  on public.categories for update
  using (public.is_admin());

drop policy if exists "admin can delete categories" on public.categories;
create policy "admin can delete categories"
  on public.categories for delete
  using (public.is_admin());

-- Storage bucket for category thumbnails
insert into storage.buckets (id, name, public)
values ('categories', 'categories', true)
on conflict (id) do nothing;

drop policy if exists "category images are publicly readable" on storage.objects;
create policy "category images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'categories');

drop policy if exists "admin can upload category images" on storage.objects;
create policy "admin can upload category images"
  on storage.objects for insert
  with check (bucket_id = 'categories' and public.is_admin());

drop policy if exists "admin can update category images" on storage.objects;
create policy "admin can update category images"
  on storage.objects for update
  using (bucket_id = 'categories' and public.is_admin());

drop policy if exists "admin can delete category images" on storage.objects;
create policy "admin can delete category images"
  on storage.objects for delete
  using (bucket_id = 'categories' and public.is_admin());
