-- 회사소개 > 인증서 섹션 — 어드민에서 추가/수정/삭제/정렬.
-- Run this in Supabase SQL editor.

-- 1) Table
create table if not exists public.certifications (
  id          bigint generated by default as identity primary key,
  title       text not null,                 -- 인증서명 (예: ISO 9001)
  subtitle    text not null default '',      -- 발급기관·설명 등 (선택)
  image_path  text not null,                 -- certifications 버킷 내 경로
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists certifications_sort_idx
  on public.certifications (sort_order);

-- 2) RLS
alter table public.certifications enable row level security;

drop policy if exists "certifications public read" on public.certifications;
create policy "certifications public read"
  on public.certifications for select
  using (true);

drop policy if exists "certifications admin write" on public.certifications;
create policy "certifications admin write"
  on public.certifications for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- 3) Storage bucket (public)
insert into storage.buckets (id, name, public)
values ('certifications', 'certifications', true)
on conflict (id) do update set public = true;

-- 4) Storage policies
drop policy if exists "certifications bucket public read" on storage.objects;
create policy "certifications bucket public read"
  on storage.objects for select
  using (bucket_id = 'certifications');

drop policy if exists "certifications bucket admin insert" on storage.objects;
create policy "certifications bucket admin insert"
  on storage.objects for insert
  with check (
    bucket_id = 'certifications'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

drop policy if exists "certifications bucket admin update" on storage.objects;
create policy "certifications bucket admin update"
  on storage.objects for update
  using (
    bucket_id = 'certifications'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

drop policy if exists "certifications bucket admin delete" on storage.objects;
create policy "certifications bucket admin delete"
  on storage.objects for delete
  using (
    bucket_id = 'certifications'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );
