-- ============================================
-- ACEWATER :: notices (공지사항)
-- Run this in Supabase Dashboard > SQL Editor
-- 관리자만 작성/수정/삭제, 누구나 조회 가능
-- ============================================

create table if not exists public.notices (
  id         bigint generated by default as identity primary key,
  author_id  uuid not null references public.profiles(id) on delete cascade,
  title      text not null,
  content    text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists notices_created_at_idx on public.notices (created_at desc);

drop trigger if exists notices_set_updated_at on public.notices;
create trigger notices_set_updated_at
  before update on public.notices
  for each row execute function public.set_updated_at();

alter table public.notices enable row level security;

drop policy if exists "notices are viewable by everyone" on public.notices;
create policy "notices are viewable by everyone"
  on public.notices for select using (true);

drop policy if exists "admin can insert notices" on public.notices;
create policy "admin can insert notices"
  on public.notices for insert with check (public.is_admin() and auth.uid() = author_id);

drop policy if exists "admin can update notices" on public.notices;
create policy "admin can update notices"
  on public.notices for update using (public.is_admin());

drop policy if exists "admin can delete notices" on public.notices;
create policy "admin can delete notices"
  on public.notices for delete using (public.is_admin());

notify pgrst, 'reload schema';
