-- 팝업 시스템 — 어드민에서 관리하는 사이트 팝업(레이어 / 일반).
-- 모바일 노출은 device 컬럼(all/pc/mobile)으로 반응형 제어.
-- Run this in Supabase SQL editor.

-- 1) Table
create table if not exists public.popups (
  id             bigint generated by default as identity primary key,
  title          text not null,

  -- 본문: 이미지 or 텍스트/HTML
  content_type   text not null default 'image',   -- 'image' | 'html'
  image_url      text,                             -- content_type='image' (외부 URL 또는 업로드된 public URL)
  body_html      text,                             -- content_type='html' (정화된 HTML)

  -- 링크
  link_url       text,
  open_new_tab   boolean not null default true,

  -- 유형 / 대상
  popup_type     text not null default 'layer',    -- 'layer' | 'general'
  device         text not null default 'all',      -- 'all' | 'pc' | 'mobile' (반응형 노출)

  -- 노출 기간
  starts_at      timestamptz not null default now(),
  ends_at        timestamptz not null,

  -- 위치 (general 유형 좌표)
  pos_x          int,
  pos_y          int,

  -- 크기 (null = 콘텐츠 크기 자동)
  width          int,
  height         int,

  -- 다시 보지 않기 옵션 ('today'=24h, 'week'=7일, 'none'=닫기만)
  dismiss_option text not null default 'today',

  -- 정렬 / 사용여부
  sort_order     int  not null default 0,          -- 작을수록 우선
  is_active      boolean not null default true,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint popups_content_type_chk check (content_type in ('image', 'html')),
  constraint popups_type_chk        check (popup_type in ('layer', 'general')),
  constraint popups_device_chk      check (device in ('all', 'pc', 'mobile')),
  constraint popups_dismiss_chk     check (dismiss_option in ('today', 'week', 'none')),
  constraint popups_period_chk      check (ends_at >= starts_at),
  constraint popups_size_chk        check (
    (width  is null or width  between 1 and 4000) and
    (height is null or height between 1 and 4000)
  )
);

-- 1b) 이전 버전을 이미 실행했다면 아래 ALTER 로 스키마를 맞춘다 (신규 생성 시엔 무해).
alter table public.popups add column if not exists dismiss_option text not null default 'today';
alter table public.popups drop column if exists quick_position;
alter table public.popups drop constraint if exists popups_type_chk;
alter table public.popups add  constraint popups_type_chk check (popup_type in ('layer', 'general'));
alter table public.popups drop constraint if exists popups_quickpos_chk;
alter table public.popups drop constraint if exists popups_dismiss_chk;
alter table public.popups add  constraint popups_dismiss_chk check (dismiss_option in ('today', 'week', 'none'));

-- 2) 인덱스 — 프론트 노출 쿼리(활성 + 기간 + 정렬)에 최적화
-- 활성 팝업만 부분 인덱스로 좁혀 스캔량을 줄임.
create index if not exists popups_live_idx
  on public.popups (sort_order, starts_at, ends_at)
  where is_active;
create index if not exists popups_admin_sort_idx
  on public.popups (sort_order, id);

-- 3) updated_at 자동 갱신
drop trigger if exists popups_set_updated_at on public.popups;
create trigger popups_set_updated_at
  before update on public.popups
  for each row execute function public.set_updated_at();

-- 4) RLS
alter table public.popups enable row level security;

-- 공개: 활성 팝업만 읽기 (비활성/예약 팝업 유출 방지 + 페이로드 축소)
drop policy if exists "popups public read active" on public.popups;
create policy "popups public read active"
  on public.popups for select
  using (is_active = true);

-- 관리자: 전체 CRUD (위 정책과 OR 로 합쳐져 관리자는 비활성 팝업도 조회 가능)
drop policy if exists "popups admin all" on public.popups;
create policy "popups admin all"
  on public.popups for all
  using (public.is_admin())
  with check (public.is_admin());

-- 5) Storage bucket (public) — 팝업 이미지 업로드용
insert into storage.buckets (id, name, public)
values ('popups', 'popups', true)
on conflict (id) do update set public = true;

drop policy if exists "popups bucket public read" on storage.objects;
create policy "popups bucket public read"
  on storage.objects for select
  using (bucket_id = 'popups');

drop policy if exists "popups bucket admin insert" on storage.objects;
create policy "popups bucket admin insert"
  on storage.objects for insert
  with check (bucket_id = 'popups' and public.is_admin());

drop policy if exists "popups bucket admin update" on storage.objects;
create policy "popups bucket admin update"
  on storage.objects for update
  using (bucket_id = 'popups' and public.is_admin());

drop policy if exists "popups bucket admin delete" on storage.objects;
create policy "popups bucket admin delete"
  on storage.objects for delete
  using (bucket_id = 'popups' and public.is_admin());
