-- ============================================
-- ACEWATER :: products (제품안내)
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================

create table if not exists public.products (
  id              bigint generated by default as identity primary key,
  category_id     bigint,                                      -- categories.id (제품안내 자식)
  name            text not null,                               -- 제품명
  model_name      text,                                        -- AW-0000
  install_type    text,                                        -- 시공타입 (multiline 가능)
  size_text       text,                                        -- 사이즈 (multiline 가능)
  material        text,                                        -- 소재
  components      jsonb not null default '[]'::jsonb,          -- [{name, target_id}]
  extras_text     text,                                        -- 별도설비
  main_image_path text not null,                               -- 대표 이미지 경로
  additional_images text[] not null default '{}',              -- 추가 이미지
  description     text not null default '',                    -- 상세 부가설명 (rich HTML)
  spec_sheet_path text,                                        -- 시방서 파일 경로
  color_chart_path text,                                       -- 색상표 파일 경로
  is_active       boolean not null default true,
  sort_order      int not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists products_category_idx on public.products (category_id);
create index if not exists products_active_sort_idx on public.products (is_active, sort_order);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

alter table public.products enable row level security;

drop policy if exists "products are viewable by everyone" on public.products;
create policy "products are viewable by everyone"
  on public.products for select using (true);

drop policy if exists "admin can insert products" on public.products;
create policy "admin can insert products"
  on public.products for insert with check (public.is_admin());

drop policy if exists "admin can update products" on public.products;
create policy "admin can update products"
  on public.products for update using (public.is_admin());

drop policy if exists "admin can delete products" on public.products;
create policy "admin can delete products"
  on public.products for delete using (public.is_admin());

-- storage bucket
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "products files are publicly readable" on storage.objects;
create policy "products files are publicly readable"
  on storage.objects for select using (bucket_id = 'products');

drop policy if exists "admin can upload products files" on storage.objects;
create policy "admin can upload products files"
  on storage.objects for insert with check (bucket_id = 'products' and public.is_admin());

drop policy if exists "admin can update products files" on storage.objects;
create policy "admin can update products files"
  on storage.objects for update using (bucket_id = 'products' and public.is_admin());

drop policy if exists "admin can delete products files" on storage.objects;
create policy "admin can delete products files"
  on storage.objects for delete using (bucket_id = 'products' and public.is_admin());

notify pgrst, 'reload schema';
