-- ============================================
-- ACEWATER :: qna (Q&A / FAQ)
-- Run this in Supabase Dashboard > SQL Editor
-- 관리자만 작성/수정/삭제, 누구나 조회 가능
-- ============================================

create table if not exists public.qna (
  id         bigint generated by default as identity primary key,
  author_id  uuid not null references public.profiles(id) on delete cascade,
  question   text not null,
  answer     text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists qna_created_at_idx on public.qna (created_at desc);

drop trigger if exists qna_set_updated_at on public.qna;
create trigger qna_set_updated_at
  before update on public.qna
  for each row execute function public.set_updated_at();

alter table public.qna enable row level security;

drop policy if exists "qna are viewable by everyone" on public.qna;
create policy "qna are viewable by everyone"
  on public.qna for select using (true);

drop policy if exists "admin can insert qna" on public.qna;
create policy "admin can insert qna"
  on public.qna for insert with check (public.is_admin() and auth.uid() = author_id);

drop policy if exists "admin can update qna" on public.qna;
create policy "admin can update qna"
  on public.qna for update using (public.is_admin());

drop policy if exists "admin can delete qna" on public.qna;
create policy "admin can delete qna"
  on public.qna for delete using (public.is_admin());

notify pgrst, 'reload schema';
