-- 우측 퀵메뉴(플로팅) 항목 — 어드민에서 추가/삭제/정렬.
-- Run this in Supabase SQL editor.

-- 1) Table
create table if not exists public.quick_menu_items (
  id          bigint generated by default as identity primary key,
  title       text not null,                 -- 최대 10자 (앱에서 검증)
  href        text not null,                 -- 링크 (http 로 시작하면 새 탭)
  icon_key    text not null default 'link',  -- lucide 아이콘 이름 (예: phone, map-pin)
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists quick_menu_items_sort_idx
  on public.quick_menu_items (sort_order);

-- 2) RLS
alter table public.quick_menu_items enable row level security;

drop policy if exists "quick_menu public read" on public.quick_menu_items;
create policy "quick_menu public read"
  on public.quick_menu_items for select
  using (true);

drop policy if exists "quick_menu admin write" on public.quick_menu_items;
create policy "quick_menu admin write"
  on public.quick_menu_items for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- 3) 기존 하드코딩 항목 시드 (테이블이 비어있을 때만)
insert into public.quick_menu_items (title, href, icon_key, sort_order)
select * from (values
  ('견적문의',   '/design-estimate',              'file-text',  1),
  ('AS센터',     '/as',                           'wrench',     2),
  ('BLOG',       'https://blog.naver.com/aw5000', 'square-pen', 3),
  ('에이스아트', 'https://www.ace-art.net/',      'building-2', 4)
) as seed(title, href, icon_key, sort_order)
where not exists (select 1 from public.quick_menu_items);
