-- ============================================
-- ACEWATER :: resources (자료실)
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================

create table if not exists public.resources (
  id             bigint generated by default as identity primary key,
  author_id      uuid not null references public.profiles(id) on delete cascade,
  title          text not null,
  content        text not null default '',
  file_path      text not null,
  file_name      text not null,
  file_size      bigint not null default 0,
  file_type      text not null default '',
  download_count int  not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists resources_created_at_idx on public.resources (created_at desc);

drop trigger if exists resources_set_updated_at on public.resources;
create trigger resources_set_updated_at
  before update on public.resources
  for each row execute function public.set_updated_at();

alter table public.resources enable row level security;

drop policy if exists "resources are viewable by everyone" on public.resources;
create policy "resources are viewable by everyone"
  on public.resources for select using (true);

drop policy if exists "admin can insert resources" on public.resources;
create policy "admin can insert resources"
  on public.resources for insert with check (public.is_admin() and auth.uid() = author_id);

drop policy if exists "admin can update resources" on public.resources;
create policy "admin can update resources"
  on public.resources for update using (public.is_admin());

drop policy if exists "admin can delete resources" on public.resources;
create policy "admin can delete resources"
  on public.resources for delete using (public.is_admin());

-- storage bucket
insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do update set public = true;

drop policy if exists "resources files are publicly readable" on storage.objects;
create policy "resources files are publicly readable"
  on storage.objects for select using (bucket_id = 'resources');

drop policy if exists "admin can upload resources files" on storage.objects;
create policy "admin can upload resources files"
  on storage.objects for insert with check (bucket_id = 'resources' and public.is_admin());

drop policy if exists "admin can update resources files" on storage.objects;
create policy "admin can update resources files"
  on storage.objects for update using (bucket_id = 'resources' and public.is_admin());

drop policy if exists "admin can delete resources files" on storage.objects;
create policy "admin can delete resources files"
  on storage.objects for delete using (bucket_id = 'resources' and public.is_admin());

-- 다운로드 수 증가 (RLS 우회용 security definer 함수)
create or replace function public.increment_resource_download(rid bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.resources set download_count = download_count + 1 where id = rid;
end;
$$;

grant execute on function public.increment_resource_download(bigint) to anon, authenticated;

notify pgrst, 'reload schema';
