-- ============================================
-- board_learn :: Supabase schema + RLS
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================

-- 1) PROFILES ----------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

-- auto-create profile when a user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, nickname)
  values (new.id, coalesce(new.raw_user_meta_data->>'nickname', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- helper: is current user admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- 2) POSTS (게시판) -----------------------------
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx on public.posts (created_at desc);

-- 3) GALLERY -----------------------------------
create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_path text not null, -- storage object path
  created_at timestamptz not null default now()
);

create index if not exists gallery_created_at_idx on public.gallery_items (created_at desc);

-- 3.5) CATEGORIES ------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete cascade,
  name text not null,
  slug text,
  image_path text,
  display_type text not null default 'tile' check (display_type in ('tile', 'link')),
  href text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists categories_parent_id_idx on public.categories (parent_id);
create index if not exists categories_sort_idx on public.categories (sort_order);

-- 4) RLS ---------------------------------------
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.gallery_items enable row level security;
alter table public.categories enable row level security;

-- profiles policies
drop policy if exists "profiles are viewable by everyone" on public.profiles;
create policy "profiles are viewable by everyone"
  on public.profiles for select
  using (true);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- posts policies (board)
drop policy if exists "posts are viewable by everyone" on public.posts;
create policy "posts are viewable by everyone"
  on public.posts for select
  using (true);

drop policy if exists "authenticated users can create posts" on public.posts;
create policy "authenticated users can create posts"
  on public.posts for insert
  with check (auth.uid() = author_id);

drop policy if exists "author or admin can update posts" on public.posts;
create policy "author or admin can update posts"
  on public.posts for update
  using (auth.uid() = author_id or public.is_admin());

drop policy if exists "author or admin can delete posts" on public.posts;
create policy "author or admin can delete posts"
  on public.posts for delete
  using (auth.uid() = author_id or public.is_admin());

-- gallery policies (admin-only writes)
drop policy if exists "gallery is viewable by everyone" on public.gallery_items;
create policy "gallery is viewable by everyone"
  on public.gallery_items for select
  using (true);

drop policy if exists "admin can insert gallery" on public.gallery_items;
create policy "admin can insert gallery"
  on public.gallery_items for insert
  with check (public.is_admin());

drop policy if exists "admin can update gallery" on public.gallery_items;
create policy "admin can update gallery"
  on public.gallery_items for update
  using (public.is_admin());

drop policy if exists "admin can delete gallery" on public.gallery_items;
create policy "admin can delete gallery"
  on public.gallery_items for delete
  using (public.is_admin());

-- categories policies
drop policy if exists "active categories are viewable by everyone" on public.categories;
create policy "active categories are viewable by everyone"
  on public.categories for select
  using (is_active = true or public.is_admin());

drop policy if exists "admin can insert categories" on public.categories;
create policy "admin can insert categories"
  on public.categories for insert
  with check (public.is_admin());

drop policy if exists "admin can update categories" on public.categories;
create policy "admin can update categories"
  on public.categories for update
  using (public.is_admin());

drop policy if exists "admin can delete categories" on public.categories;
create policy "admin can delete categories"
  on public.categories for delete
  using (public.is_admin());

-- 5) STORAGE bucket for gallery images --------
insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('categories', 'categories', true)
on conflict (id) do nothing;


-- storage RLS
drop policy if exists "gallery images are publicly readable" on storage.objects;
create policy "gallery images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'gallery');

drop policy if exists "admin can upload gallery images" on storage.objects;
create policy "admin can upload gallery images"
  on storage.objects for insert
  with check (bucket_id = 'gallery' and public.is_admin());

drop policy if exists "admin can update gallery images" on storage.objects;
create policy "admin can update gallery images"
  on storage.objects for update
  using (bucket_id = 'gallery' and public.is_admin());

drop policy if exists "admin can delete gallery images" on storage.objects;
create policy "admin can delete gallery images"
  on storage.objects for delete
  using (bucket_id = 'gallery' and public.is_admin());

drop policy if exists "category images are publicly readable" on storage.objects;
create policy "category images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'categories');

drop policy if exists "admin can upload category images" on storage.objects;
create policy "admin can upload category images"
  on storage.objects for insert
  with check (bucket_id = 'categories' and public.is_admin());

drop policy if exists "admin can update category images" on storage.objects;
create policy "admin can update category images"
  on storage.objects for update
  using (bucket_id = 'categories' and public.is_admin());

drop policy if exists "admin can delete category images" on storage.objects;
create policy "admin can delete category images"
  on storage.objects for delete
  using (bucket_id = 'categories' and public.is_admin());

-- 6) updated_at trigger for posts -------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();
