-- ============================================
-- ACEWATER :: tags (통합 태그 관리)
-- product / qna 등 다양한 영역의 태그를 한 테이블에서 관리
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================

create table if not exists public.tags (
  id          bigint generated by default as identity primary key,
  scope       text not null check (scope in ('product', 'qna')),
  value       text not null,
  label       text not null,
  tone        text not null default 'neutral'
              check (tone in ('blue', 'red', 'amber', 'neutral', 'green', 'purple')),
  sort_order  int  not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (scope, value)
);
create index if not exists tags_scope_idx on public.tags (scope);
create index if not exists tags_active_sort_idx on public.tags (is_active, sort_order);

drop trigger if exists tags_set_updated_at on public.tags;
create trigger tags_set_updated_at
  before update on public.tags
  for each row execute function public.set_updated_at();

alter table public.tags enable row level security;

drop policy if exists "tags are viewable by everyone" on public.tags;
create policy "tags are viewable by everyone"
  on public.tags for select using (true);

drop policy if exists "admin can insert tags" on public.tags;
create policy "admin can insert tags"
  on public.tags for insert with check (public.is_admin());

drop policy if exists "admin can update tags" on public.tags;
create policy "admin can update tags"
  on public.tags for update using (public.is_admin());

drop policy if exists "admin can delete tags" on public.tags;
create policy "admin can delete tags"
  on public.tags for delete using (public.is_admin());

-- 기본 시드 — 이미 있으면 갱신 안 함
insert into public.tags (scope, value, label, tone, sort_order) values
  ('product', 'new',          'NEW',      'blue',    10),
  ('product', 'best',         'BEST',     'red',     20),
  ('product', 'recommended',  'PICK',     'amber',   30),
  ('product', 'featured',     '대표',     'neutral', 40),
  ('product', 'pet',          '반려견용', 'amber',   50),
  ('product', 'accessible',   '장애인용', 'blue',    60),
  ('qna',     'product',      '제품문의', 'blue',    10),
  ('qna',     'repair',       '수리문의', 'red',     20),
  ('qna',     'parts',        '부품문의', 'amber',   30),
  ('qna',     'docs',         '자료문의', 'neutral', 40),
  ('qna',     'installation', '시공문의', 'green',   50),
  ('qna',     'etc',          '기타문의', 'neutral', 90)
on conflict (scope, value) do nothing;

-- Q&A 에 태그 컬럼 추가
alter table public.qna
  add column if not exists tags text[] not null default '{}';

notify pgrst, 'reload schema';
